pipeline {
    agent {label 'slave1'}
    
    parameters {
        string(name: 'IMAGETAG', defaultValue: '', description: 'Parameter from CI pipeline')  
    }

    stages {

        stage("Checkout from SCM") {
               steps {
                   git branch: 'feat-131-dockerize', credentialsId: 'github', url: 'https://github.com/Ashfaque-9x/gitops-register-app'
               }
        }
        
        stage('Getting Image from CI pipeline') {
            steps {
                script{
                    echo "Image: ${params.IMAGETAG}"
                }
            }
        }

        stage("Update the README") {
            steps {
                script{
                    sh """
                       cat README.md
                       sed -i 's/Wanderlust/Wanderlust-Updated with Version-${params.IMAGETAG}/g' README.md
                       cat README.md
                    """
                }
            }
        }

        stage('Pushing latest Image to Github') {
            steps {
                script{
                    sh """
                        git config --global user.name "DevMadhup"
                        git config --global user.email "littledevopsengineer@gmail.com"
                        git add README.md
                        git commit -m "Updated README"
                        """
                        withCredentials([gitUsernamePassword(credentialsId: 'Github', gitToolName: 'Default')]) {
                            sh "git push origin main -ff"
                    }
                }
            }
        }
    }
}
